const KEY='tsumoriq-data-v0.000.001';
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const fmtMonth=d=>d.toLocaleDateString('nl-BE',{month:'long',year:'numeric'});
const money=(n,c='€')=>`${c}${Number(n||0).toFixed(2).replace('.',',')}`;
const daysBetween=(a,b)=>Math.round((new Date(b)-new Date(a))/(1000*60*60*24));
const initial={settings:{name:'',currency:'€',distance:0,home:'Thuis',work:'Werk',mode:'Motor'},trips:[],expenses:[],lastBackupReminder:'',lastReportPrompt:''};
let state=load();let viewDate=new Date();let deferredPrompt=null;
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function setScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(`screen-${name}`).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));if(name==='report')renderReport();if(name==='achievements')renderBadges()}
function ym(date){return date.toISOString().slice(0,7)}
function inMonth(item){return item.date&&item.date.slice(0,7)===ym(viewDate)}
function monthItems(){return {trips:state.trips.filter(inMonth),expenses:state.expenses.filter(inMonth)}}
function render(){document.getElementById('currentMonthLabel').textContent=fmtMonth(viewDate);const {trips,expenses}=monthItems();const km=trips.reduce((s,t)=>s+Number(t.km||0),0);const cost=expenses.reduce((s,e)=>s+Number(e.amount||0),0);document.getElementById('statTrips').textContent=trips.length;document.getElementById('statKm').textContent=km.toFixed(1).replace('.',',');document.getElementById('statCost').textContent=money(cost,state.settings.currency);document.getElementById('statReceipts').textContent=expenses.filter(e=>e.receipt).length;renderGreeting();renderRecent();fillSettings();if(document.getElementById('screen-report').classList.contains('active'))renderReport();}
function renderGreeting(){const name=state.settings.name||'daar';document.getElementById('greeting').textContent=`Goedemorgen ${name} 👋`;const today=todayISO();const logged=[...state.trips,...state.expenses].some(x=>x.date===today);const streak=calcStreak();document.getElementById('streakText').textContent=logged?`Vandaag gelogd. ${streak} dagen streak.`:`Vandaag nog niets gelogd.`;document.getElementById('motivation').textContent=streak>0?`Goed bezig. Je administratie is al ${streak} dag(en) consequent.`:'Begin met één tik. Ook thuiswerk telt.'}
function calcStreak(){let d=new Date();let count=0;while(true){const iso=d.toISOString().slice(0,10);const has=[...state.trips,...state.expenses].some(x=>x.date===iso);if(!has)break;count++;d.setDate(d.getDate()-1)}return count}
function renderRecent(){const list=document.getElementById('recentList');const rows=[...state.trips.map(t=>({...t,type:'trip'})),...state.expenses.map(e=>({...e,type:'expense'}))].sort((a,b)=>(b.createdAt||b.date).localeCompare(a.createdAt||a.date)).slice(0,8);if(!rows.length){list.className='list empty-state';list.textContent='Nog geen logs.';return}list.className='list';list.innerHTML=rows.map(x=>`<div class="log-row"><div><strong>${x.type==='trip'?iconMode(x.mode)+' '+x.mode+' · '+x.purpose:'🧾 '+x.category}</strong><small>${x.date}${x.type==='trip'?' · '+(x.km||0)+' km':' · '+money(x.amount,state.settings.currency)}</small></div><span class="pill">${x.type==='trip'?'rit':'kost'}</span></div>`).join('')}
function iconMode(m){return {Motor:'🏍',Auto:'🚗',Fiets:'🚲',OV:'🚆','Te voet':'🚶'}[m]||'➜'}
function quickCommute(mode){const s=state.settings;state.trips.unshift({id:uid(),date:todayISO(),mode,from:s.home||'Thuis',to:s.work||'Werk',km:Number(s.distance||0),purpose:'Woon-werk',notes:'Quick log',createdAt:new Date().toISOString()});save();toast(`${mode} woon-werk gelogd`)}
function quickHome(){state.trips.unshift({id:uid(),date:todayISO(),mode:'Thuiswerk',from:'Thuis',to:'Thuis',km:0,purpose:'Thuiswerk',notes:'Thuis gewerkt',createdAt:new Date().toISOString()});save();toast('Thuiswerk gelogd')}
async function compressImage(file){return new Promise((resolve)=>{const img=new Image();const reader=new FileReader();reader.onload=e=>{img.onload=()=>{const max=900;let w=img.width,h=img.height;if(w>h&&w>max){h*=max/w;w=max}else if(h>max){w*=max/h;h=max}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.72))};img.src=e.target.result};reader.readAsDataURL(file)})}
function renderReport(){const {trips,expenses}=monthItems();const currency=state.settings.currency;const byMode={};trips.forEach(t=>{byMode[t.mode]=(byMode[t.mode]||0)+Number(t.km||0)});const byPurpose={};expenses.forEach(e=>{byPurpose[e.purpose]=(byPurpose[e.purpose]||0)+Number(e.amount||0)});const html=`<h2>${state.settings.name||'Gebruiker'} · ${fmtMonth(viewDate)}</h2><p>Lokale rapportage, gegenereerd op ${new Date().toLocaleDateString('nl-BE')}.</p><h3>Samenvatting</h3><table class="report-table"><tr><th>Ritten</th><td>${trips.length}</td></tr><tr><th>Kilometers</th><td>${trips.reduce((s,t)=>s+Number(t.km||0),0).toFixed(1)} km</td></tr><tr><th>Kosten</th><td>${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),currency)}</td></tr><tr><th>Bonnetjes</th><td>${expenses.filter(e=>e.receipt).length}</td></tr></table><h3>Km per vervoer</h3><table class="report-table">${Object.entries(byMode).map(([k,v])=>`<tr><th>${k}</th><td>${v.toFixed(1)} km</td></tr>`).join('')||'<tr><td>Geen ritten</td></tr>'}</table><h3>Kosten per type</h3><table class="report-table">${Object.entries(byPurpose).map(([k,v])=>`<tr><th>${k}</th><td>${money(v,currency)}</td></tr>`).join('')||'<tr><td>Geen kosten</td></tr>'}</table><h3>Ritten</h3><table class="report-table"><tr><th>Datum</th><th>Vervoer</th><th>Van → Naar</th><th>Km</th><th>Type</th></tr>${trips.map(t=>`<tr><td>${t.date}</td><td>${t.mode}</td><td>${t.from||''} → ${t.to||''}</td><td>${t.km||0}</td><td>${t.purpose}</td></tr>`).join('')}</table><h3>Kosten</h3><table class="report-table"><tr><th>Datum</th><th>Categorie</th><th>Vervoer</th><th>Bedrag</th><th>Type</th></tr>${expenses.map(e=>`<tr><td>${e.date}</td><td>${e.category}</td><td>${e.mode}</td><td>${money(e.amount,currency)}</td><td>${e.purpose}</td></tr>`).join('')}</table><p style="margin-top:28px">Handtekening / controle: ___________________________</p>`;document.getElementById('reportContent').innerHTML=html}
function reportText(){const {trips,expenses}=monthItems();return `Tsumoriq rapport ${fmtMonth(viewDate)}\nRitten: ${trips.length}\nKm: ${trips.reduce((s,t)=>s+Number(t.km||0),0).toFixed(1)}\nKosten: ${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),state.settings.currency)}\nBonnetjes: ${expenses.filter(e=>e.receipt).length}\n\nOpen de app om het volledige rapport als PDF te printen.`}
const badges=[['🥉','Eerste rit',()=>state.trips.length>=1],['🧾','10 bonnetjes',()=>state.expenses.filter(e=>e.receipt).length>=10],['📚','100 bonnetjes',()=>state.expenses.filter(e=>e.receipt).length>=100],['🔥','7 dagen gelogd',()=>calcStreak()>=7],['🏁','100 dagen in de app',()=>uniqueDays()>=100],['📅','365 dagen in de app',()=>uniqueDays()>=365],['🏍','1000 km geregistreerd',()=>state.trips.reduce((s,t)=>s+Number(t.km||0),0)>=1000],['🏠','10 thuiswerkdagen',()=>state.trips.filter(t=>t.purpose==='Thuiswerk').length>=10]];
function uniqueDays(){return new Set([...state.trips,...state.expenses].map(x=>x.date)).size}
function renderBadges(){document.getElementById('badgeList').innerHTML=badges.map(([icon,name,test])=>`<div class="badge ${test()?'':'locked'}"><div class="icon">${icon}</div><strong>${name}</strong><p class="muted">${test()?'Vrijgespeeld':'Nog te behalen'}</p></div>`).join('')}
function fillSettings(){const s=state.settings;settingName.value=s.name||'';settingCurrency.value=s.currency||'€';settingDistance.value=s.distance||'';settingHome.value=s.home||'';settingWork.value=s.work||'';settingMode.value=s.mode||'Motor'}
function setTodayInputs(){tripDate.value=todayISO();expenseDate.value=todayISO();tripFrom.value=state.settings.home||'Thuis';tripTo.value=state.settings.work||'Werk';tripKm.value=state.settings.distance||'';tripMode.value=state.settings.mode||'Motor'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});
installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;installBtn.classList.add('hidden')}};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));
document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>b.dataset.action==='workhome'?quickHome():quickCommute(b.dataset.mode));
openTripForm.onclick=()=>{setScreen('log');document.querySelector('[data-tab="trip"]').click()};openExpenseForm.onclick=()=>{setScreen('log');document.querySelector('[data-tab="expense"]').click()};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');tripForm.classList.toggle('active-form',t.dataset.tab==='trip');expenseForm.classList.toggle('active-form',t.dataset.tab==='expense')});
prevMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};nextMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};
tripForm.onsubmit=e=>{e.preventDefault();state.trips.unshift({id:uid(),date:tripDate.value,mode:tripMode.value,from:tripFrom.value,to:tripTo.value,km:Number(tripKm.value||0),purpose:tripPurpose.value,notes:tripNotes.value,createdAt:new Date().toISOString()});tripNotes.value='';save();toast('Rit opgeslagen')};
receiptFile.onchange=async e=>{const f=e.target.files[0];if(f){receiptPreview.src=await compressImage(f);receiptPreview.classList.remove('hidden')}};
expenseForm.onsubmit=e=>{e.preventDefault();state.expenses.unshift({id:uid(),date:expenseDate.value,category:expenseCategory.value,mode:expenseMode.value,amount:Number(expenseAmount.value||0),purpose:expensePurpose.value,notes:expenseNotes.value,receipt:receiptPreview.src||'',createdAt:new Date().toISOString()});expenseAmount.value='';expenseNotes.value='';receiptFile.value='';receiptPreview.src='';receiptPreview.classList.add('hidden');save();toast('Kost opgeslagen')};
settingsForm.onsubmit=e=>{e.preventDefault();state.settings={name:settingName.value,currency:settingCurrency.value||'€',distance:Number(settingDistance.value||0),home:settingHome.value||'Thuis',work:settingWork.value||'Werk',mode:settingMode.value};save();setTodayInputs();toast('Setup opgeslagen')};
printReport.onclick=()=>window.print();emailReport.onclick=()=>{location.href=`mailto:?subject=${encodeURIComponent('Tsumoriq rapport '+fmtMonth(viewDate))}&body=${encodeURIComponent(reportText())}`};
exportJson.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tsumoriq-backup-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href)};
importJson.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...initial,...JSON.parse(r.result)};save();toast('Backup geïmporteerd')}catch{toast('Ongeldig JSON-bestand')}};r.readAsText(f)};
clearData.onclick=()=>{if(confirm('Alles verwijderen?')){state=structuredClone(initial);save();toast('Data gewist')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
setTodayInputs();render();
